const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const FETCH_POSTS = "FETCH_POSTS";
const FETCH_POST = "FETCH_POST";
const FETCH_USERS = "FETCH_USERS";
const FOLLOW_USER = "FOLLOW_USER";
const UNFOLLOW_USER = "UNFOLLOW_USER";
const CREATE_POST = "CREATE_POST";
const EDIT_POST = "EDIT_POST";
const DELETE_POST = "DELETE_POST";
const LIKE_POST = "LIKE_POST";
const UNLIKE_POST = "UNLIKE_POST";
const UPDATE_USER_INFO = "UPDATE_USER_INFO";
const CREATE_USER_DOC = "CREATE_USER_DOC";

export {
  SIGN_IN,
  SIGN_OUT,
  FETCH_POSTS,
  CREATE_POST,
  FETCH_POST,
  FETCH_USERS,
  EDIT_POST,
  DELETE_POST,
  LIKE_POST,
  UNLIKE_POST,
  UPDATE_USER_INFO,
  CREATE_USER_DOC,
  FOLLOW_USER,
  UNFOLLOW_USER,
};
