const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const FETCH_POSTS = "FETCH_POSTS";
const FETCH_POST = "FETCH_POST";
const CREATE_POST = "CREATE_POST";
const EDIT_POST = "EDIT_POST";
const DELETE_POST = "DELETE_POST";

export {
  SIGN_IN,
  SIGN_OUT,
  FETCH_POSTS,
  CREATE_POST,
  FETCH_POST,
  EDIT_POST,
  DELETE_POST,
};
